# Build the Fortran IV/77 programs
#
# --- constants
FORTRAN=gfortran
FFLAGS=-g -O2 -Wline-truncation -Wsurprising -Werror
BIN=.
EXEC=.
SRC=.
FDEPENDS=$(SRC)/mercury.inc $(SRC)/swift.inc

# --- Help
help:
	@echo
	@echo 'Supported Makefile invocations:'
	@echo 'make build	- Build the Fortran programs as needed'
	@echo 'make unbuild	- Remove all Fortran program executables'
	@echo 'make gen-in	- Generate input files by copying them from samples'
	@echo 'make rm-gen	- Remove all files generated by the Fortran programs'
	@echo 'make rm-in	- Remove all input files used by the Fortran programs'
	@echo

# --- Build Fortran programs
build:	$(BIN)/close6 $(BIN)/element6 $(BIN)/mercury6

$(BIN)/close6:	$(FDEPENDS) $(SRC)/close6.for
	$(FORTRAN) $(FFLAGS) -o $(BIN)/close6 $(SRC)/close6.for

$(BIN)/element6:	$(FDEPENDS) $(SRC)/element6.for
	$(FORTRAN) $(FFLAGS) -o $(BIN)/element6 $(SRC)/element6.for

$(BIN)/mercury6:	$(FDEPENDS) $(SRC)/mercury6_2.for
	$(FORTRAN) $(FFLAGS) -o $(BIN)/mercury6 $(SRC)/mercury6_2.for

# --- Remove executable files
unbuild:
	rm -f $(BIN)/element6 $(BIN)/close6 $(BIN)/mercury6

# --- Generate input files from samples 
# --- *.in copied from corresponding *.in.sample
gen-in:
	for FILE in $(EXEC)/*.sample; do \
		cp $$FILE `echo $$FILE | sed 's/.sample//g'`; \
	done

# --- Remove files generated by Fortran programs
rm-gen:
	rm -f $(EXEC)/{ *.dmp *.clo *.out *.tmp *.aei } 2> /dev/null

# --- Remove input files to the Fortran programs
rm-in:
	rm -f $(EXEC)/*.in 2> /dev/null

# --- end ---
